# Generated by Django 5.1.1 on 2024-10-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_type',
            field=models.CharField(choices=[('French', 'french'), ('Chinese', 'chinese'), ('Italian', 'italian'), ('Balkan', 'balkan'), ('Other', 'other')], max_length=7),
        ),
    ]
