# Generated by Django 5.1.1 on 2024-10-06 07:48

import tastyRecipesApp.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[tastyRecipesApp.user.validators.validate_nickname_min_length])),
                ('first_name', models.CharField(max_length=30, validators=[tastyRecipesApp.user.validators.validate_name_capitalized])),
                ('last_name', models.CharField(max_length=30, validators=[tastyRecipesApp.user.validators.validate_name_capitalized])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
